"""Initial schema with User and AccessLog tables

Revision ID: 8b864ec1a2c3
Revises: 
Create Date: 2026-02-03 11:12:12.069895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b864ec1a2c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=500), nullable=False),
    sa.Column('email', sa.String(length=500), nullable=False),
    sa.Column('telefone', sa.String(length=500), nullable=False),
    sa.Column('data_nascimento', sa.String(length=500), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=False),
    sa.Column('mac', sa.String(length=17), nullable=True),
    sa.Column('mac_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('access_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('access_logs', schema=None) as batch_op:
        batch_op.create_index('idx_timestamp_id', ['timestamp', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_logs_access_id'), ['access_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_access_logs_ip_hash'), ['ip_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_logs_mac_hash'), ['mac_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reset_token', sa.String(length=64), nullable=True),
    sa.Column('reset_expires', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('access_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_access_logs_mac_hash'))
        batch_op.drop_index(batch_op.f('ix_access_logs_ip_hash'))
        batch_op.drop_index(batch_op.f('ix_access_logs_access_id'))
        batch_op.drop_index('idx_timestamp_id')

    op.drop_table('access_logs')
    # ### end Alembic commands ###
